debug: true
log:
  pretty: true
  level: "trace"
server:
  address: "0.0.0.0:8080"
  read-timeout: "1s"
  write-timeout: "3s"
  idle-timeout: "2m"
  shutdown-timeout: "5s"
db:
  host: "mysql"
  port: 3306
  user: "starter"
  password: "starter"
  dbname: "starter"
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  parse-time: true
  location: Asia/Tehran
  max-life-time: "5m"
  max-idle-time: "0s"
  max-open-connections: 10
  max-idle-connections: 5
