name: build

on: push

permissions:
  contents: read

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dev.Dockerfile
          push: false
          tags: miladabc/golang-starter-dev:latest

  build-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: miladabc/golang-starter:latest
