name: ci

on: push

permissions:
  contents: read

env:
  GO_VERSION: 1.23.5

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4.3
        ports:
          - 3306:3306
        env:
          TZ: Asia/Tehran
          MYSQL_DATABASE: starter
          MYSQL_USER: starter
          MYSQL_PASSWORD: starter
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: test
        uses: robherley/go-test-action@v0

  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: go-mod-tidy
        uses: j0hnsmith/go-mod-check@v1

  golangci-lint:
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_VERSION: v1.63.4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  build-dev:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dev.Dockerfile
          push: false
          tags: miladabc/golang-starter-dev:latest

  build-prd:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: miladabc/golang-starter:latest
