name: qualify

on: push

permissions: {}

jobs:
  golangci-lint:
    name: lint
    permissions:
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      # pull-requests: read
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.23.5
      GOLANGCI_LINT_VERSION: v1.63.4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
