name: qualify

on: push

permissions: {}

env:
  GO_VERSION: 1.23.5

jobs:
  go-mod-tidy:
    name: tidy
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: tidy
        uses: j0hnsmith/go-mod-check@v1

  golangci-lint:
    name: lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_VERSION: v1.63.4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
